### ISSUE TITLE
Where's My Old School Range Warning?

### ISSUE THREAD

**Issue by TripleEYE** [tullamods/OmniCC#129]
On the previous version of OmniCC I could set it up so the Range Warning shows red on all of the Button as opposed to the Hotkey only.
I don't see that setting anywhere now. Where is it? I loved it and now to have that functionality I need to  stack up another addon :o 
Please bring it back :crying_cat_face:

**Comment by ceylina** [comment]
http://www.curse.com/addons/wow/tullarange

Perhaps this? Looks like Tuller made it a stand alone addon

**Comment by Tuller** [comment]
Out of range coloring was never part of omnicc






On Tue, May 12, 2015 at 9:12 AM -0700, "ceylina" <notifications@github.com> wrote:












http://www.curse.com/addons/wow/tullarange



Perhaps this? Looks like Tuller made it a stand alone addon

**Comment by TripleEYE** [comment]
What do you mean? Out of range collor was and still IS part of OmniCC... I have downgraded and CONFIRMED that in version 6.0, the out of range was the whole button. And now it's STILL THERE, only the option to make the whole button red in not there anymore, instead you just get the keys red.
I'd use version 6.0 if it wasn't broken in other manners.

As for tullaRange - I've tried it and they seem to conflict (they didn't use to in Burning Crusade).
But it has since updated. So I'll gladly try again ^_^

**Comment by Tuller** [comment]
Red key binding text is standard on all action bars (try without omnicc and you should get the same result).





On Thu, May 14, 2015 at 11:13 AM -0700, "TripleEYE" <notifications@github.com> wrote:












What do you mean? Out of range collor was and still IS part of OmniCC... I have downgraded and CONFIRMED that in version 6.0, the out of range was the whole button. And now it's STILL THERE, only the option to make the whole button red in not there anymore, instead you just get the keys red.

I'd use version 6.0 if it wasn't broken in other manners.



As for tullaRange - I've tried it and they seem to conflict (they didn't use to in Burning Crusade).

But it has since updated. So I'll gladly try again ^_^

**Comment by TripleEYE** [comment]
I see.. ok but version 6.0 still did have what I'm talking about... it was
a checkbox...
