### ISSUE TITLE
"Activate" finish effect animation issue.

### ISSUE THREAD

**Issue by ls-** [tullamods/OmniCC#152]
Hi!

There's a conflict between OmniCC and oUF, and pretty much any other addon that has buttons w/ cooldown spirals and `button.overlay` element 😢 Because you use `ActionBarButtonSpellActivationAlert` template, you also inherit all of its scripts and some script handlers do nasty things.

Please, remove or replace script handlers [here](https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/ActionBarFrame.xml#L111) and [here](https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/ActionBarFrame.xml#L163-L168), because they are [bad](https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/ActionButton.lua#L610-L616) 😁

**Comment by nitz** [comment]
As from my reference in #72, I think it may be related to this. I was able to grab some screenshots of the frame stacks -- OmniCC's frames do seem to be getting stuck on these components. In my case, it seems to be the frames named "<frame anchored to>OmniCCActivateAnts" that gets stuck

Frame on Shadowed Unit Frame auras: ![wowscrnshot_082416_201001](https://cloud.githubusercontent.com/assets/602691/17952407/50527c92-6a38-11e6-81b1-3b17907c69f0.jpg)

Frame on TipTac auras: ![wowscrnshot_082416_200958](https://cloud.githubusercontent.com/assets/602691/17952417/633f3534-6a38-11e6-9f8d-b056e5dcc8c2.jpg) (this one was hard to get, because as I'd attempt to mouse over, the tooltip would disappear, but the "activation" effect is the one you can see in the first screenshot. It's interesting, because when the parent frame faded out, so would the activation frame, but when the tooltip would reshow, the "Ants" frame would still be stuck on it!
