### ISSUE TITLE
Addon Action Blocked

### ISSUE THREAD

**Issue by Mardleseyth** [tullamods/OmniCC#177]
4x [ADDON_ACTION_BLOCKED] AddOn 'OmniCC' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function `Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function `SetMapAreaID'
FrameXML\WorldMapFrame.lua:390: in function <FrameXML\WorldMapFrame.lua:353>
[C]: ?
[C]: in function `Hide'
FrameXML\UIParent.lua:2320: in function `SetUIPanel'
FrameXML\UIParent.lua:2347: in function `MoveUIPanel'
FrameXML\UIParent.lua:2378: in function `HideUIPanel'
FrameXML\UIParent.lua:2052: in function <FrameXML\UIParent.lua:2044>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2846: in function `HideUIPanel'
FrameXML\UIParent.lua:2812: in function `ToggleFrame'
FrameXML\WorldMapFrame.lua:219: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

This has started coming up since using the most recent build of Omni_CC coupled with the 7.1 patch.

**Comment by KJanos1396** [comment]
Same error:
12/1 00:22:41.700  An action was blocked in combat because of taint from OmniCC_Config - CompactRaidFrame2:Show()
12/1 00:22:41.700      Interface\FrameXML\CompactUnitFrame.lua:339 CompactUnitFrame_UpdateVisible()
12/1 00:22:41.700      Interface\FrameXML\CompactUnitFrame.lua:280 CompactUnitFrame_UpdateAll()
12/1 00:22:41.700      Interface\FrameXML\CompactUnitFrame.lua:115
12/1 00:22:44.249  Interface\FrameXML\UIParent.lua:2004
