### ISSUE TITLE
Revert Cooldown:SetHideCountdownNumbers

### ISSUE THREAD

**Issue by Znuff** [tullamods/OmniCC#235]
So late in the life-cycle of an addon that is very popular, this change is not a good idea.

Addons have adapted to using different techniques to prevent OmniCC from showing cooldown text.

This change requires users (and addon authors) to change how their UI works considerably.

Please reconsider obeying this setting.

**Comment by Tuller** [comment]
This won’t be reverted but it’ll probably be an option. Supporting SetHideCountdownNumbers let’s me more cleanly hide things that Blizzard doesn’t want countdowns on, like the HonorLevel display

**Comment by InfusOnWoW** [comment]
Okay after testing this a bit. Apparently OmniCC is now observing SetHideCountdownNumbers, which is terrible for WA.

We explicitly call SetHideCountdownNumbers(true) if omnicc is loaded, because that's the best default to prevent having both blizzard and omnicc show a number.

**Comment by Tuller** [comment]
I assumed things like this would happen, thus the reason for a beta and why it’ll be an option before it’s actually released (and likely disabled by default).

Blizzard’s usage of the API is their own version of the noCooldownCount flag that OmniCC implements, which is why I wanted to obey it

**Comment by InfusOnWoW** [comment]
Please inform us what we need to do, once you figure iut out. A PM is appreciated.

**Comment by ascott18** [comment]
If OmniCC is going to commandeer `SetHideCountdownNumbers`, then it should probably also commandeer cVar `countdownForCooldowns` and force it to `0`.

This is why TellMeWhen, WeakAuras, and others are setting `SetHideCountdownNumbers(true)` whenever OmniCC is loaded - because OmniCC doesn't suppress the Blizzard numbers, and we don't want every single user to know that they have to go into the Blizzard interface settings and turn off the Blizz numbers (ActionBars -> Show Numbers for Cooldowns). Many users would never figure this out, and would sooner bombard us with bug reports that they're seeing two timer text numbers on top of one another.

**Comment by Tuller** [comment]
@InfusOnWoW I've reverted the change in the latest beta. I decided that if I did make it optional, it would have made less sense than the optimize performance option in earlier versions of OmniCC. 
@ascott18, OmniCC has actually had a `SetCVar('countdownForCooldowns', 0)`. It was unintentionally dropped from the previous version and I've added it back.

**Comment by ascott18** [comment]
Gotcha - I did my CTRL+F on that version, so that would explain why I didn't find it.
