### ISSUE TITLE
Fel rush first stack

### ISSUE THREAD

**Issue by zorixx** [tullamods/OmniCC#261]
Hello, since the 8.0.3 my first charge of fel rush is considered as a normal CD and not as a restoring charge.

**Comment by Tuller** [comment]
This is the behavior I'm getting:

Recharging, with a charge available to use:
![image](https://user-images.githubusercontent.com/191239/45850366-d6bc0d00-bd03-11e8-9ebd-8a6793934830.png)

Recharging, but zero charges available:
![image](https://user-images.githubusercontent.com/191239/45850395-fce1ad00-bd03-11e8-86b9-c8bc57382790.png)

The intent is that a recharging cooldown signifies "You're down a charge, but you can still use this ability" and the other styling is, "You can't use this ability for X seconds"

**Comment by zorixx** [comment]
Since 8.0.3 i always have like the 2nd screenshot without touching any options just by updating. It seems to be link to Tellmewhen from what i just see.

8.0.1:
![fr 8 0 1](https://user-images.githubusercontent.com/43408579/45851145-98d9db80-bd39-11e8-9500-d14ef8b32177.png)

8.0.5:
![fr 8 0 1](https://user-images.githubusercontent.com/43408579/45851154-a727f780-bd39-11e8-8791-3c708216eb77.png)

**Comment by Tuller** [comment]
So that is because I changed the code that determines if something is a charge or not. This is what it looks like in the current versions of timer.lua
```lua
local function cooldown_GetKind(cooldown)
    if cooldown.currentCooldownType == COOLDOWN_TYPE_LOSS_OF_CONTROL then
        return "loc"
    end

    local parent = cooldown:GetParent()
    if parent and parent.chargeCooldown == cooldown then
        return "charge"
    end

    return "default"
end
```
This is what it would look like if you changed it to be closer to how 8.0.1 does the check:
```lua
local function cooldown_GetKind(cooldown)
    if cooldown.currentCooldownType == COOLDOWN_TYPE_LOSS_OF_CONTROL then
        return "loc"
    end

    -- 8.0.1 and earlier behavior for charge cooldown detection
    if not cooldown:GetDrawSwipe() then
        return "charge"
    end

    return "default"
end
```
I changed from `not cooldown:GetDrawSwipe()` because that check is a guess based off of how a cooldown looks and not what it is intended to be. The `parent.chargeCooldown == cooldown` check is more indicative of that, and works with pretty much all action bar addons.

**Comment by zorixx** [comment]
Thanks for your time !
