### ISSUE TITLE
Not working good with NamePlateKAI

### ISSUE THREAD

**Issue by shena1983** [tullamods/OmniCC#282]
OmniCC 8.0.9
NamePlateKAI 8.0.74
Assassination Rogue 
debuff duration text always missing. please fix it.
<img width="417" alt="screen shot 2018-11-15 at 7 54 28 pm" src="https://user-images.githubusercontent.com/9585924/48551394-65b66180-e910-11e8-874d-d96980a86703.png">

**Comment by Tuller** [comment]
The reason this one doesn't work for OmniCC is a bit complicated. To explain, this is what OmniCC looks like for a typical cooldown:
![image](https://user-images.githubusercontent.com/191239/48666574-c4b8d980-eabc-11e8-9ae5-c18960f0c79c.png)
That is, there's an ability (action, buff, spell) with a cooldown object (the spiral), and OmniCC's cooldown text. The ability frame contains the icon, and there's a cooldown spiral + omnicc's text display as children.

In the case of an action button, it looks more like this:
![image](https://user-images.githubusercontent.com/191239/48666597-f893ff00-eabc-11e8-81e1-74f47092f853.png)
That is, there's the potential of multiple cooldown spirals for a single ability. In order to not display multiple cooldown texts, OmniCC picks the most relevant one and parks its text display over the cooldown it picked.

Now for the case of NamePlateKAI:
![image](https://user-images.githubusercontent.com/191239/48666674-3e04fc00-eabe-11e8-8ac8-fc8cefbc0e61.png)
The icon for a cooldown is intermingled with the spiral, and all cooldowns on a nameplate share a common parent.  OmniCC is again only showing text for one of those cooldowns, in this case the one with the shortest duration remaining.

I don't really have a fix for this one at the moment.

**Comment by shena1983** [comment]
very clear explanation.

**Comment by shena1983** [comment]
Temporary solution for me：
disable some codes in omnicc and nameplateKAI to prevent cvar countdownForCooldowns changed.
change settings let nameplateKAI use biz default cooldown count.
change settings let omnicc disable cooldown count for default group.
use omnicc only  for TWM and TargetFrameDebuff...

Looking forward to the new version of OmniCC.
![wechatimg9219](https://user-images.githubusercontent.com/9585924/48681694-ee6a2180-ebde-11e8-8ae8-1260b40eaf5d.jpeg)
