### ISSUE TITLE
Text positions off due to SetScale since 8.3.2

### ISSUE THREAD

**Issue by jcai1** [tullamods/OmniCC#329]
The 8.3.2 update caused changes for text positioning; the positioning is dependent on the scale % such that it's impossible to maintain a fixed offset position if you have several different sizes.

For example: in one of my rules I had cooldown text offset with x=0 y=6 (CENTER anchored to CENTER). This offset would stay constant regardless of the scale (soon=125%, under a minute=100%, under an hour=90%, etc). However this is no longer the case after the 8.3.2 update. For example, the red "soon" text would be centered higher.

I traced this to the use of SetScale(). Previously the scale for the FontString was always 1 but now it varies based on the scale% specified for soon/minute/hour/etc. The problem is that this scale also affects the offset. An x=0 y=6 offset with a scale of 125% actually becomes a x=0 y=7.5 offset when finally displayed.

**Comment by Jaliborc** [comment]
Good to know, thanks

**Comment by BuurmanDeBuurman** [comment]
I'm sorry I can't provide more of a detailed problem description as the person above, but the OmniCC text positions are way out of wack for me as well. The positions are all different between ShadowedUnitFrames, Bartender and WeakAuras even though they initially used the same ruleset and "resize cooldown text to fit within frame". I never had issues with this until 8.2-8.3. They all aligned perfectly but since a few weeks I had to manually set everything up and even now, the sizes an alignment is way off between for example Bartender buttons on the left side of my screen and those on the right side. There is no way to align it perfectly for every single frame it affects and I am not being a control freak here. Can provide screenshots if needed.

**Comment by Tuller** [comment]
Are you still having issues with this?

**Comment by BuurmanDeBuurman** [comment]
At first glance it seems better but I'll update if I notice something in the next few days.
