### ISSUE TITLE
Vudho Hot Squares

### ISSUE THREAD

**Issue by pandho** [tullamods/OmniCC#355]
With the newest version (9.0.6) some of my vuhdo hot squares don't show a countdown swipe and just look like they're about to run out. I can kind of fix it by hotting everyone up and opening / closing vuhdo, but that doesn't work for all buffs. I reinstalled 9.0.5 and the bug is gone.

**Comment by Tuller** [comment]
Are you using the cooldown opacity option set to zero by chance?

**Comment by malonysaintpierre** [comment]
So i've been through hell the last 2 days trying to fix this.
I've made a theme with a rule for vuhdo, omnicc ignores it, tried to change minimum size to all extremes, nothing changes, only disabling the addon fixed, now i'm blessed to find this and reinstall the old version.

Opening vuhdo panel while putting hots makes them work, sort of, looks like omni is overwriting vuhdo's settings.
Screenshot of how it looks.
I didnt change anything in any setting before having this problem, happened after the update, only fixed by disabling the addon or reverting to the old version (1 every 10-20 hots would eventually pop up properly with a clock, again, feels like omni is having a conflict with vuhdo on who sets the rules on those frames- even with a rule to disable them)
https://imgur.com/a/khDhFr6

**Comment by pandho** [comment]
> Do you have cooldown opacity set to zero?

No, I didn't. Moving the slider around fixes the the issue (as far as i can tell).
But then i have no cooldown swipe for the spell icons in my action bars as well.
And i can't quite figure out, how to make a theme only for the vuhdo frames, so i can adjust the opacity slider only for them.

**Comment by Nickkontscha** [comment]
I have the same issue with the current version of OmniCC and Vuhdo. Opacity is at 100%. It happes on Vuhdo HoTs / Bouquets.

**Comment by ferganette** [comment]
Change the Opacity in OmniCC to zero and it fixes the issue with Vuhdo.

**Comment by Nickkontscha** [comment]
> Change the Opacity in OmniCC to zero and it fixes the issue with Vuhdo.

Yeah, but then you dont see the CD of the ability anymore which is the main functionality of OmniCC

**Comment by Tuller** [comment]
Try the 9.0.8 release for this. I no longer override cooldown opacity if you leave it at the default value (100%). This should hopefully fix this issue.

**Comment by pandho** [comment]
Seems to be working fine. Thank you very much!
